server:
  port: 9001

spring:
  application:
    name: task-producer
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

# configure Kafka binder
spring.cloud.stream.kafka.binder:
  brokers: ${kafka.brokers}
  auto-create-topics: false # disable topic creation by Spring Cloud Stream
  configuration:
    group.id: task-producer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

spring.cloud.stream.bindings:
  results:
    destination: results
    consumer:
      useNativeDecoding: true
      headerMode: headers
  tasks:
    destination: tasks
    producer:
      useNativeEncoding: true
      headerMode: headers

# configure topic provisioning
kafka.provision:
  brokers: ${kafka.brokers}
  topics:
    - name: ${tasks.topic}
      numPartitions: ${tasks.topic.partitions}
      replicationFactor: ${tasks.topic.replication.factor}
      configs:
        cleanup.policy: ${tasks.topic.cleanup.policy}
        retention.ms: ${tasks.topic.retention.ms}
    - name: ${results.topic}
      numPartitions: ${results.topic.partitions}
      replicationFactor: ${results.topic.replication.factor}
      configs:
        cleanup.policy: ${results.topic.cleanup.policy}
        retention.ms: ${results.topic.retention.ms}

logging:
  level:
    org.apache.kafka.clients.producer: WARN